SPRING_APPLICATION_NAME=StudentManagement
SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/StudentManagement
SPRING_DATASOURCE_USERNAME=root
SPRING_DATASOURCE_PASSWORD=kiyohara
SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
MYBATIS_CONFIGURATION_MAP_UNDERSCORE_TO_CAMEL_CASE=true
MYBATIS_MAPPER_LOCATIONS=classpath*:mapper/*.xml